### ISSUE TITLE
Determine strategy for handling URLs that map to multiple SPDX identifiers

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/licensee#28] opened 2021-05-21 20:33 UTC
For example, the androidx.emoji library uses http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web which maps to OFL-1.1, OFL-1.1-no-RFN, and OFL-1.1-RFN. Right now, we map URL to SPDX identifier based on the first seen in the JSON which isn't great.

Should we accept any SPDX identifier of the three and have them match any dependency with this license URL?

**Comment by hfhbd** [comment] 2023-05-05 06:39
Isn't this a duplicate of https://github.com/cashapp/licensee/issues/86?

**Comment by JakeWharton** [comment] 2023-05-05 12:39
I still think we grab only a single SPDX ID from a URL. Given the behavior of 'or' now, mapping to all possible IDs seems reasonable.

**Comment by hfhbd** [comment] 2023-05-05 13:19
Wanna have a PR? :D

**Comment by JakeWharton** [comment] 2023-05-05 13:25
Always. And then I am going to doing the release because it's getting large.

**Closed** 2023-05-05 19:07 UTC
Labels: bug, spdx
