### ISSUE TITLE
Missing dependencies in artifacts.json 

### ISSUE THREAD

**Issue by SmialyKot** [cashapp/licensee#212] opened 2023-05-24 07:46 UTC
When analyzing `artifacts.json` which I wanted to use to display included open-source libraries, I've noticed that some dependencies were missing - the most notable of which was [Moshi](https://github.com/square/moshi).

I've created a barebones reproduction - an app straight out of the Android Studio template with Moshi and Licensee: https://github.com/SmialyKot/LicenseeTestApp

The output of `./gradlew licensee` task is included in `licensee` directory.
Any idea what might be the issue here?

**Comment by hfhbd** [comment] 2023-06-16 08:10
Interesting, I minified the reproducer:
```
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.8.22'
    id 'app.cash.licensee' version '1.7.0'
}

dependencies {
    implementation "com.squareup.moshi:moshi:1.15.0"
}

licensee {
    allow('Apache-2.0')
}
```
[LicenseeTestApp-main.zip](https://github.com/cashapp/licensee/files/11767861/LicenseeTestApp-main.zip)

Results into:
```
com.squareup.okio:okio:2.10.0
 - SPDX identifier 'Apache-2.0' allowed
org.jetbrains:annotations:13.0
 - SPDX identifier 'Apache-2.0' allowed
org.jetbrains.kotlin:kotlin-stdlib:1.8.22
 - SPDX identifier 'Apache-2.0' allowed
org.jetbrains.kotlin:kotlin-stdlib-common:1.8.22
 - SPDX identifier 'Apache-2.0' allowed
org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22
 - SPDX identifier 'Apache-2.0' allowed
org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22
 - SPDX identifier 'Apache-2.0' allowed
```
This is the pom file of moshi: https://repo1.maven.org/maven2/com/squareup/moshi/moshi/1.15.0/moshi-1.15.0.pom
I didn't find any special things, so I guess we need further debugging.

**Comment by babogoos** [comment] 2023-08-25 04:51
Same here.
When I use the third party library `'io.github.andreypfau:curve25519-kotlin:0.0.6'` which is licensed by [GPL-3](https://github.com/turbogiants/curve25519-kotlin/blob/master/LICENSE).

It was supposed to fail on licensee task, but it passed the task.

Then I check the `artifacts.json`, the dependencies were missing.

I've tried to use [dependency tree diff](https://github.com/JakeWharton/dependency-tree-diff) tools to check if the dependencies were not detectable, but it worked as expected.

![截圖 2023-08-25 下午12 35 32](https://github.com/cashapp/licensee/assets/1038449/bc78d839-c839-4faa-a0cd-70d31b9e6293)

It might have some bugs when generating the dependency tree on the licensee task.

Please let me know if you need any additional information from me.

**Comment by gabrielittner** [comment] 2023-09-10 07:16
I wanted to look into this but at least for me the issue is not happening anymore when using `1.8.0-SNAPSHOT`.

**Comment by JakeWharton** [comment] 2023-09-10 14:06
That's a good sign. I'll try the above sample tomorrow and see if it's fixed, too.

**Comment by JakeWharton** [comment] 2023-09-12 01:59
Yep, fixed in the samples, too. Moshi shows up now.

**Closed as completed by JakeWharton** 2023-09-12 01:59 UTC

**Comment by gabrielittner** [comment] 2023-09-21 07:34
@JakeWharton Would it be possible to get a release with this?

**Comment by JakeWharton** [comment] 2023-09-21 17:08
Yes! It's been on my list of TODOs, but I'm at a conference this week. In about 3.5 hours I'll be done with my talk and can try to sneak it in, but if not it'll be early next week.
