### ISSUE TITLE
No license found for compose (desktop) modules

### ISSUE THREAD

**Issue by warting** [cashapp/licensee#58] opened 2021-10-08 14:31 UTC
I am using composereorderable (https://repo1.maven.org/maven2/org/burnoutcrew/composereorderable/reorderable/0.6.2/) and this tool says it has no licenses even though it has the apache 2 license.

The reason seems to be that one of the artifacts is not having any resolvedFiles. If it has no files, it is safe to assume that no license is needed for that? I've made a PR that solves my issue, but I'm not sure it is the correct approach to solve it.

Please have a look https://github.com/cashapp/licensee/pull/57

**Comment by JakeWharton** [comment] 2022-07-12 15:37
Going to close as a duplicate of #30 which is fixed in 1.5.0. Please try and let me know if it resolves this. Otherwise we'll have to get a failing test case integrated.

**Closed as completed by JakeWharton** 2022-07-12 15:37 UTC
